export const users = [
  {
    id: 1,
    name: "María González",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    nivel: "plata",                 
    puntos: 45,                     
    medallas: ["basico", "bronce", "plata"], 
  },
  {
    id: 2,
    name: "Carlos Ruiz",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    nivel: "bronce",
    puntos: 20,
    medallas: ["basico", "bronce"],
  },
  {
    id: 3,
    name: "Ana Martínez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    nivel: "oro",
    puntos: 70,
    medallas: ["basico", "bronce", "plata", "oro"],
  },
]
export const recipes = [
  {
    id: 1,
    title: "Pasta Carbonara Clásica",
    description: "Una receta tradicional italiana con un sabor increíble. Perfecta para una cena rápida y deliciosa.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3",
    category: "Italiana",
    difficulty: "Media",
    time: 30,
    servings: 4,
    author: "María González",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop",
    nivel: "plata",
    likes: 45,
    liked: false,
    ingredients: ["400g de spaghetti", "200g de guanciale", "4 yemas de huevo", "100g de queso pecorino", "Pimienta negra al gusto"],
    instructions: [
      "Cocer la pasta en agua con sal hasta al dente.",
      "Freír el guanciale hasta que quede crujiente.",
      "Mezclar yemas con queso y pimienta.",
      "Unir pasta caliente con guanciale y la mezcla de huevos fuera del fuego."
    ],
    videoUrl: "https://www.youtube.com/embed/3AAdKl1UYZs",
  },
  {
    id: 2,
    title: "Tarta de Chocolate Belga",
    description: "Un postre decadente y rico en chocolate. Ideal para ocasiones especiales.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
    category: "Postres",
    difficulty: "Difícil",
    time: 60,
    servings: 8,
    author: "Carlos Ruiz",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop",
    nivel: "bronce",
    likes: 67,
    liked: true,
    ingredients: ["200g de chocolate negro 70%", "150g de mantequilla", "3 huevos", "150g de azúcar", "100g de harina"],
    instructions: [
      "Derretir chocolate y mantequilla al baño maría.",
      "Batir huevos con azúcar hasta blanquear.",
      "Incorporar la mezcla de chocolate.",
      "Agregar harina y mezclar bien.",
      "Hornear a 180°C por 25 minutos."
    ],
    videoUrl: "https://www.youtube.com/embed/bqBulLgQwZM",
  },
  {
    id: 3,
    title: "Ensalada César Fresca",
    description: "Una ensalada clásica con aderezo casero y croutons crujientes.",
    image: "https://images.unsplash.com/photo-1551248429-40975aa4de74",
    category: "Ensaladas",
    difficulty: "Fácil",
    time: 20,
    servings: 2,
    author: "Ana Martínez",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop",
    nivel: "oro",
    likes: 32,
    liked: false,
    ingredients: ["1 lechuga romana", "100g de parmesano", "Pan para croutons", "2 filetes de anchoa", "Jugo de limón"],
    instructions: [
      "Cortar la lechuga en trozos grandes.",
      "Preparar los croutons al horno.",
      "Hacer el aderezo mezclando anchoas, limón y parmesano.",
      "Mezclar todo y servir."
    ],
    videoUrl: "https://www.youtube.com/embed/qKM3oKqsYsc",
  },
  {
    id: 4,
    title: "Sushi Roll Variado",
    description: "Aprende a hacer sushi casero con diferentes rellenos.",
    image: "https://images.unsplash.com/photo-1553621042-f6e147245754",
    category: "Asiática",
    difficulty: "Media",
    time: 45,
    servings: 4,
    author: "María González",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=40&h=40&fit=crop",
    nivel: "plata",
    likes: 89,
    liked: true,
    ingredients: ["2 tazas de arroz para sushi", "4 hojas de nori", "200g de salmón fresco", "1 aguacate", "Salsa de soja"],
    instructions: [
      "Cocinar el arroz y sazonar con vinagre de arroz.",
      "Extender el arroz sobre el nori.",
      "Agregar el relleno y enrollar.",
      "Cortar en piezas y servir."
    ],
    videoUrl: "https://www.youtube.com/embed/9oEBf3XfqZ8",
  },
  {
    id: 5,
    title: "Tacos al Pastor",
    description: "Auténticos tacos mexicanos con carne marinada y piña.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47",
    category: "Mexicana",
    difficulty: "Media",
    time: 40,
    servings: 6,
    author: "Carlos Ruiz",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=40&h=40&fit=crop",
    nivel: "bronce",
    likes: 54,
    liked: false,
    ingredients: ["500g de cerdo", "Chiles guajillo", "Piña natural", "Tortillas de maíz", "Cilantro y cebolla"],
    instructions: [
      "Marinar la carne con los chiles y especias.",
      "Cocinar la carne en trompo o plancha.",
      "Calentar tortillas.",
      "Montar los tacos con piña y cilantro."
    ],
    videoUrl: "https://www.youtube.com/embed/tMrnHs0Tpqk",
  },
  {
    id: 6,
    title: "Bowl Saludable de Quinoa",
    description: "Un bowl nutritivo lleno de vegetales frescos y proteína.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
    category: "Saludable",
    difficulty: "Fácil",
    time: 25,
    servings: 2,
    author: "Ana Martínez",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=40&h=40&fit=crop",
    nivel: "oro",
    likes: 41,
    liked: false,
    ingredients: ["1 taza de quinoa", "Garbanzos asados", "Pepino y tomate cherry", "Aguacate", "Limón y aceite de oliva"],
    instructions: [
      "Cocer la quinoa según instrucciones.",
      "Asar los garbanzos con especias.",
      "Cortar los vegetales frescos.",
      "Montar el bowl y aderezar."
    ],
    videoUrl: "https://www.youtube.com/embed/x2B3jU9Zy2s",
  },
]

export const categories = ["Todas", "Italiana", "Mexicana", "Asiática", "Postres", "Ensaladas", "Saludable", "Vegetariana", "Sopas"]

export const forumPosts = [
  {
    id: 1,
    title: "¿Cuál es tu técnica favorita para hacer pan?",
    author: "María González",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    nivel: "plata",
    date: "7/2/2026",
    category: "Técnicas",
    content: "Estoy empezando a hacer pan casero y me gustaría conocer sus mejores consejos y técnicas.",
    likes: 12,
    replies: 2,
    comments: [
    {
    author: "Carlos Ruiz",
    nivel: "bronce",
    date: "Hace 2 días",
    text: "Lo más importante es la temperatura del agua",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop"
  }
]
  },
  {
    id: 2,
    title: "Ideas para meal prep de la semana",
    author: "Ana Martínez",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    nivel: "oro",
    date: "8/2/2026",
    category: "Planificación",
    content: "¿Qué recetas preparan con anticipación para la semana?",
    likes: 8,
    replies: 1,
  },
  {
    id: 3,
    title: "¿Cuchillo de chef o santoku?",
    author: "Carlos Ruiz",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    nivel: "bronce",
    date: "9/2/2026",
    category: "Equipamiento",
    content: "Estoy buscando mi primer cuchillo bueno y no sé cuál elegir. ¿Qué recomiendan?",
    likes: 15,
    replies: 5,
  },
  {
    id: 4,
    title: "Sustitutos del huevo en repostería",
    author: "María González",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    nivel: "plata",
    date: "10/2/2026",
    category: "Ingredientes",
    content: "¿Qué usan para reemplazar el huevo en recetas veganas? Tengo un cliente con alergia.",
    likes: 20,
    replies: 8,
  },
]

export const trendingByCountry = [
  { country: "Estados Unidos", recipe: "BBQ Ribs", category: "Americana", lat: 39, lng: -98 },
  { country: "México", recipe: "Tacos al Pastor", category: "Mexicana", lat: 23, lng: -102 },
  { country: "España", recipe: "Paella Valenciana", category: "Española", lat: 40, lng: -4 },
  { country: "Italia", recipe: "Pizza Napolitana", category: "Italiana", lat: 42, lng: 12 },
  { country: "Francia", recipe: "Croissants", category: "Francesa", lat: 46, lng: 2 },
  { country: "Alemania", recipe: "Schnitzel", category: "Alemana", lat: 51, lng: 10 },
  { country: "Japón", recipe: "Ramen Tonkotsu", category: "Japonesa", lat: 36, lng: 138 },
  { country: "India", recipe: "Butter Chicken", category: "India", lat: 20, lng: 77 },
  { country: "Brasil", recipe: "Feijoada", category: "Brasileña", lat: -10, lng: -55 },
  { country: "Argentina", recipe: "Asado", category: "Argentina", lat: -34, lng: -64 },
]
